### ISSUE TITLE
Expose repositories instance methods instead of class methods

### ISSUE THREAD

**Issue by jodosha** [hanami/model#290]
## Actual

We use class methods from repositories. For instance `BookRepository.find`. This approach has a couple of pitfalls:

  * We are forced to assign a class level adapter (`BookRepository.adapter = adapter`) before the application starts. We should reduce as much as possible global state.

  * Class methods resist refactoring

  * Dependency injection should work with instances. Having repositories as instances helps to use DI in projects.

## Proposal

Use instance methods for the default CRUD operations that we expose. Example.

```ruby
BookRepository.new.find(1)
```

**This is a breaking change**

---

Related articles:

  * http://blog.codeclimate.com/blog/2012/11/14/why-ruby-class-methods-resist-refactoring/
  * http://nicksda.apotomo.de/2011/07/are-class-methods-evil/
  * http://andrzejonsoftware.blogspot.it/2011/07/yes-nick-class-methods-are-evil.html

**Comment by pascalbetz** [comment]
@jodosha


I think this is a very good change! Class methods almost always lead to trouble and bad design.
I can give it a try.

**Comment by hlegius** [comment]
It will be a good and welcome improvement in an OOD perspective. :ok_hand:

**Comment by joneslee85** [comment]
Will you consider keep class method as transitional interface for backward-comparability for one or two releases before killing them off completely?

**Comment by pascalbetz** [comment]
I would prefer to have a clean cut. Less confusion.

**Comment by pascalbetz** [comment]
@jodosha 

I read through the source code. Repository has ```adapter``` and ```collection``` injected through ```Collection._configure_repository!```.

How would the repository get hold of those when not static anymore? Constructor? Lookup?

**Comment by jodosha** [comment]
@joneslee85 

> Will you consider keep class method as transitional interface for backward-compatability for one or two releases before killing them off completely?

We're introducing breaking changes with the next milestone. It's probably better to ship all of them at once. So developers will know that this release will change how they work with data layer.

**Comment by jodosha** [comment]
@pascalbetz I'd like to introduce small steps. For now, just leave everything as it is, just make CRUD interface available at the instance level.

We can't make that kind of decisions now, without considering the outcome of #292

**Comment by pascalbetz** [comment]
@jodosha ok, this is what i went with.

This is what I did:
Move the current class methods to instance methods. Make accessors for ```adapter``` and ```collection``` at the instance level that forward to the class level. 

What do you think?

**Comment by jodosha** [comment]
@pascalbetz That's what we needed!

**Comment by Bounga** [comment]
I understand the benefits in regards with Hanami code maintainability but for the end-user it's a bit cumbersome to call `BookRepository.new.find(1)`. He won't see any immediate benefit when using it.

Maybe we could have convenience class methods that wrap it?

`BookRepository.find(1)` => `BookRepository.new.find(1)`

As a programmer it's awkward to think that I have to instantiate an object when I don't need one, just because it eases the code quality of the framework I'm using. As a user of the framework, I'd like to have a nice looking / easy to use interface.

So once again I understand this proposal but it could be nice to add a more "natural" interface to use over it.

**Comment by pascalbetz** [comment]
@Bounga 

It kind of defeats the purpose. When we want to get rid of class level configuration, then we can not provide class level access. First step is to only remove class level access to repo operations but keep the class level config. So during that time it would still be possible. But i'd rather have people switch how they use repositories sooner than later.

> As a programmer it's awkward to think that I have to instantiate an object when I don't need one, just because it eases the code quality of the framework I'm using. As a user of the framework, I'd like to have a nice looking / easy to use interface.

A programmer should understand why there is no class level access. And one who does not know should try to figure it out and learn:-)
And code quality is not just a byproduct. I think it is crucial to a framework because it is much more long living than applications built with that framework.

**Comment by pascalbetz** [comment]
@jodosha @joneslee85 @AlfonsoUceda and of course everybody else: Feedback welcome: https://github.com/hanami/model/pull/299

**Comment by pascalbetz** [comment]
@joneslee85 updated.

**Comment by jodosha** [comment]
@Bounga 

> Maybe we could have convenience class methods that wrap it?

This would have two negative effects, it will **double** the public API and nobody will use the instance level methods, because nobody force them to do so.

**Comment by AlfonsoUceda** [comment]
closing because of #299
