### ISSUE TITLE
Inherited entities not exposing base attributes

### ISSUE THREAD

**Issue by accuser** [hanami/model#306]
From the documentation:

```ruby
require 'hanami/model'

class Article
  include Hanami::Entity
  attributes :name
end

class RareArticle < Article
  attributes :price
end

RareArticle.attributes
=> #<Set: {:price}>
article = RareArticle.new(name:'Rare', price:100)
 => #<RareArticle:0x007fa68ca7b568 @price=100> 
article.to_h
 => {:price=>100} 
```

I'm expecting all the attributes (including inherited) to be available via `#attributes` and `#to_h`.

**Comment by jodosha** [comment]
@accuser Thanks for reporting this problem.
@hlegius This is something that you should take in account while working on #292 Thanks! :+1:

**Comment by hlegius** [comment]
@jodosha sure. My pleasure :tophat:

**Comment by cllns** [comment]
@fteem `hanami-model` is currently being reworked by @jodosha to be based on [`rom`](https://github.com/rom-rb/rom).
You can see work here: https://github.com/hanami/model/tree/new-engine

This issue should be fixed by that effort. (If it's not, it'll need to be fixed in the new code, not this current existing code)

**Comment by jodosha** [comment]
I manually merged this PR to fix the problem https://github.com/hanami/model/pull/316

The fork is: https://github.com/gramo-org/model and `fix_inherited_attributes` is the branch.
