### ISSUE TITLE
Includes that extend the objects 

### ISSUE THREAD

**Issue by mereghost** [hanami/model#319]
Hi there,

I was mucking around the code and got glimpse of a certain "rail-ism" on [repository.rb](https://github.com/hanami/model/blob/master/lib/hanami/repository.rb#L132).

The whole `include InstanceMethods` and `extend ClassMethods` have been somewhat abandoned even in Rails (that started the practice) since it was considered harmful. Josh Cheek makes the point way better than I'll ever be able to [here](http://blog.8thlight.com/josh-cheek/2012/02/03/modules-called-they-want-their-integrity-back.html) .

The question is: is there any plan, or way (*did not mess around enough to know*) to refactor that, at least removing the `InstanceMethods` part?

**Comment by jodosha** [comment]
@mereghost Hey, thanks for spotting this problem. That `InstanceMethods` was recently introduced by #299 and I haven't noticed it when merged. I agree this is a design flaw which is unique for this case.

I'm [reworking repositories](https://github.com/hanami/model/blob/master/.github/PULL_REQUEST_TEMPLATE.md), so this refactoring isn't necessary because the implementation will change a lot. Thanks Marcello!
