### ISSUE TITLE
Current power of associations

### ISSUE THREAD

**Issue by beauby** [hanami/model#344]
All available associations examples only deal with a single association at a time.

* Can multiple associations be aggregated at the same time? Answer: yes, `aggregate` takes a variable number of symbols as arguments (source: ROM source code)
* Can multiple levels of association be aggregated at the same time? Short answer: not really at the moment. Longer answer: not via `aggregate`, but it is possible via `RelationProxy#combine`, which allows only one-level of configured associations, so for nested associations (for instance a user and their posts and their posts' comments) the API is more complicated and needs the associations' relations to be explicited. [Here](https://github.com/rom-rb/rom-repository/pull/40) is a pending PR by yours truly to extend `#combine`'s API to support nested hashes of configured association symbols.
* Can multiple associations be used at the same time for creation? Answer: I don't know.
* Can multiple levels of associations be used at the same time for creation? Answer: I don't know.

**Comment by jodosha** [comment]
@beauby I'm sorry, but this kind of issues are left behind because are more a discussion than an actionable request (bug, enhancement, feature).

At this point in time, we're focused on shipping Hanami 1.0 as it is and then to iterate where needed. Associations deserve more love for sure. But it will require a Community effort to improve their design.

Closing this as not actionable.
