### ISSUE TITLE
Outdated dependencies

### ISSUE THREAD

**Issue by thegeorgeous** [hanami/model#664]
Several dependencies are far behind their latest versions. `dry-types` is locked to 0.11 when the latest version is 1.5. The dep-fu PRs were closed and deleted.

**Comment by jodosha** [comment]
@thegeorgeous This is because the actual stable version of `hanami-model` targets ROM 3.

For Hanami 2.0, it will target ROM 5.

**Comment by kkpxebia** [comment]
Sorry to comment on a closed issue, but this is still a problem.
Current stable version of hanami-model says that: **This branch contains the code for hanami-model 2.x.**
And in the gemspec we still have **  spec.add_runtime_dependency "rom",             "~> 3.3", ">= 3.3.3"**
So did the plan change and hanami-model wont upgrade to ROM5?
Currently this gem produces a lot of dependencies problem for older apps that try to upgrade. I am currently trying to up an app to ruby 2.7.x and there is a problem with bigdecimal (because of sequel 4.9 dependency, I saw some old issue for this) and dry-types, which uses 0.x version. This conflicts with most other libraries that also use dry-types, for example grape, which requires dry-types 1.1.1 at least.
